# Step 2.1: Kustomization File | With the help of kustomization, expand by adding DB migration processing for dev

resources:
  - deployment.yaml
  - db-migration.yaml

commonLabels:
  environment: dev

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: my-app-deployment
    spec:
      template:
        spec:
          containers:
            - name: my-app-container
              env:
                - name: ENVIRONMENT
                  value: "dev"
