# Step 1: Base Deployment Configurations | Create a basic k8s deployment for the application

apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-application
  labels:
    app: your-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-application
  template:
    metadata:
      labels:
        app: your-application
    spec:
      containers:
      - name: your-application-container
        image: your-application-image:latest
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80