# Extend Stage from dev by adding replicas:2 and readinessProbe
resources:
- ../dev

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: your-application
    spec:
      replicas: 2
      template:
        spec:
          containers:
          - name: your-application-container
            readinessProbe:
              httpGet:
                path: /health
                port: 80
              initialDelaySeconds: 5
              periodSeconds: 10
