resources:
- ../stage

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: your-application
    spec:
      template:
        spec:
          initContainers: null
