resources:
  - ../stage

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: your-application
    spec:
      template:
        spec:
          initContainers: []